# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 08:03
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
